### ISSUE TITLE
Expiry Placeholder is truncated

### ISSUE THREAD

**Issue by SikandAlex** [yassram/YRPayment#3]
<img width="341" alt="Screen Shot 2019-09-12 at 11 54 45 PM" src="https://user-images.githubusercontent.com/12959962/64836626-ce19b200-d5b8-11e9-9380-6b0190306844.png">

**Comment by SikandAlex** [comment]
how can I fix this?

**Comment by asikand** [comment]
I had to manually import OcraStd.otf font file into the root directory of my project and then add it to the fontsProvidedByApplication part of Info.plist to get this fixed.

**Comment by SikandAlex** [comment]
I had to manually import OcraStd.otf font file into the root directory of my project and then add it to the fontsProvidedByApplication part of Info.plist to get this fixed.

**Comment by yassram** [comment]
Fixed issue ! 
Thank's @SikandAlex for the reporting !
